### ISSUE TITLE
Lien vers le changelog

### ISSUE THREAD

**Issue by FabriceGo** [phifi92/Monitoring#29]
Bonjour @phifi92 

Pouvez vous m'indiquer ou ce trouve le dépôt de la documentation du plugin Monitoring ?
=> En fait, je voudrais compléter le changelog

Et j'ai une autre modification à proposer bientôt (lié aux RPi ARM61).

Merci.

**Comment by phifi92** [comment]
Bonjour,

Pour moi la doc doit être mise à jour lors du push en stable, que j'ai justement fait ce jour.
Ajout fait dans le changelog.

OK pour tes futurs PR

Merci
Cdt
