### ISSUE TITLE
Possible incompatibilité avec le plugin VMWare

### ISSUE THREAD

**Issue by FabriceGo** [phifi92/Monitoring#43]
Bonjour,

voir ici pour le détail :
https://community.jeedom.com/t/erreur-sur-monitoring/113434/30

Ou se trouve la documentation pour contribuer au changelog ?
Merci.

**Comment by phifi92** [comment]
Bonjour,
Un est en warning, l'autre en error fatal....
Changelog a jour avec l'info qu'il est nécessaire de réinstaller les dépendances.
Cdt
Phifi

**Comment by FabriceGo** [comment]
Merci pour ta réponse. Bonne journée.
