### ISSUE TITLE
Re-installation des dependances suite à la mise à jour pour debian 12

### ISSUE THREAD

**Issue by megastorage** [phifi92/Monitoring#44]
Salut,

Pour eviter cela,

Il faut créer un fichier:
plugin_info/packages.json

Tu peux regarder sur mon plugin:
https://github.com/megastorage/Nut_Free/blob/master/plugin_info/packages.json

A dispo.

Stéphane.

**Comment by phifi92** [comment]
Salut,

Merci à toi pour se partage.
Cdt
