### ISSUE TITLE
Erreur sur Monitoring::pull() : Call to undefined function floaval()

### ISSUE THREAD

**Issue by chrisalex-dev** [phifi92/Monitoring#51]
bonjour,

depuis la mise à jour de la version du 29/10 sur jeedom je rencontre l'erreur :
Erreur sur Monitoring::pull() : Call to undefined function floaval()

Je vous vous remercie pour votre support

**Comment by notesbancales** [comment]
Même souci,
L'erreur apparaît toutes les 15min visible dans le moteur des tâches (state=error)
J'ai réinstallé les dépendances, redémarré la VM, sans succès.
J'ai voulu refaire un équipement, erreur 500 au moment de la sauvegarde, même chose sur l'équipement déjà créé.
Jeedom 4.3.18, Debian 11 sur freebox delta

Merci pour votre temps.

**Comment by chrisalex-dev** [comment]
Résolu avec la mise à jour d'hier soir

**Comment by chrisalex-dev** [comment]
Résolu avec la mise à jour d'hier soir
